<div align="left">
    <img src="https://raw.githubusercontent.com/ElProfeAlejo/Bootcamp_Databases/main/imagenes/email_arriba.png" alt="Texto alternativo" width="50%">


#**¿Qué es Numpy?**

NumPy es una biblioteca clave en Python para manejar grandes cantidades de datos de manera eficiente. Te permite crear arrays (listas de datos más potentes que las listas normales de Python) y realizar operaciones matemáticas sobre ellos de manera súper rápida. Por ejemplo, si quieres sumar, restar o multiplicar todos los elementos de un arreglo, lo puedes hacer en una sola línea de código, sin necesidad de usar bucles.

Documentación: https://numpy.org/doc/stable/

#**1. Importando Numpy**

### Importando todo el paquete

In [ ]:
import numpy
numpy.__version__

'1.26.4'

In [ ]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando todo el paquete y asignándole un nuevo nombre

In [ ]:
import numpy as np

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando parte del paquete

In [ ]:
from numpy import arange

In [ ]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#**2. Creando arrays Numpy**

### A partir de listas

In [ ]:
km = np.array([1000, 2300, 4987, 1500])

In [ ]:
km

array([1000, 2300, 4987, 1500])

In [ ]:
type(km)

numpy.ndarray

In [ ]:
km.dtype

dtype('int64')

### A partir de datos externos

In [ ]:
km = np.loadtxt(fname='motos-km.txt', dtype = int)

In [ ]:
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [ ]:
km.dtype

dtype('int64')

### Arrays con dos dimensiones

In [ ]:
datos = [
    ['Llantas de aleación', 'Cerraduras de seguridad', 'Bolsas laterales', 'Asientos personalizados', 'Puños calefaccionados', 'Espejos retrovisores deportivos', 'Protecciones para manos', 'Iluminación LED'],
    ['Sistema de navegación', 'Techo desmontable', 'Frenos ABS', 'Suspensión ajustable', 'Panel digital', 'Puños calefaccionados', 'Asientos ergonómicos', 'Cámara de reversa'],
    ['Control de tracción', 'Iluminación adaptativa', 'Frenos de disco', 'Transmisión automática', 'Asientos de cuero', 'Sistema de audio', 'Ventanas de seguridad', 'Frenos ABS']
]
datos

[['Llantas de aleación',
  'Cerraduras de seguridad',
  'Bolsas laterales',
  'Asientos personalizados',
  'Puños calefaccionados',
  'Espejos retrovisores deportivos',
  'Protecciones para manos',
  'Iluminación LED'],
 ['Sistema de navegación',
  'Techo desmontable',
  'Frenos ABS',
  'Suspensión ajustable',
  'Panel digital',
  'Puños calefaccionados',
  'Asientos ergonómicos',
  'Cámara de reversa'],
 ['Control de tracción',
  'Iluminación adaptativa',
  'Frenos de disco',
  'Transmisión automática',
  'Asientos de cuero',
  'Sistema de audio',
  'Ventanas de seguridad',
  'Frenos ABS']]

In [ ]:
Accesorios = np.array(datos)

In [ ]:
Accesorios

array([['Llantas de aleación', 'Cerraduras de seguridad',
        'Bolsas laterales', 'Asientos personalizados',
        'Puños calefaccionados', 'Espejos retrovisores deportivos',
        'Protecciones para manos', 'Iluminación LED'],
       ['Sistema de navegación', 'Techo desmontable', 'Frenos ABS',
        'Suspensión ajustable', 'Panel digital', 'Puños calefaccionados',
        'Asientos ergonómicos', 'Cámara de reversa'],
       ['Control de tracción', 'Iluminación adaptativa',
        'Frenos de disco', 'Transmisión automática', 'Asientos de cuero',
        'Sistema de audio', 'Ventanas de seguridad', 'Frenos ABS']],
      dtype='<U31')

In [ ]:
Accesorios.shape

(3, 8)

In [ ]:
km.shape

(258,)

### Comparando desempeño con listas

In [ ]:
np_array = np.arange(1000000)

In [ ]:
py_list = list(range(1000000))

In [ ]:
%time for _ in range(100): np_array *= 2

CPU times: user 72.8 ms, sys: 0 ns, total: 72.8 ms
Wall time: 73.7 ms


In [ ]:
%time for _ in range(100): py_list = [x*2 for x in py_list]

CPU times: user 9.93 s, sys: 3.44 s, total: 13.4 s
Wall time: 13.6 s


#**3. Operaciones aritméticas con arrays Numpy**

### Operaciones entre arrays y constantes

In [31]:
km = [44410., 5712., 37123., 0., 25757.]
años = [2003, 1991, 1990, 2019, 2006]

In [ ]:
edad = 2024 - años

In [35]:
km = np.array([44410., 5712., 37123., 0., 25757.])
años = np.array([2003, 1991, 1990, 2019, 2006])

In [38]:
edad = 2024 - años

In [39]:
edad

array([21, 33, 34,  5, 18])

### Operaciones entre arrays

In [40]:
km_media = km / edad

In [41]:
km_media

array([2114.76190476,  173.09090909, 1091.85294118,    0.        ,
       1430.94444444])

In [42]:
44410. / 21

2114.7619047619046

### Operaciones con arrays de dos dimensiones

In [43]:
km = [44410., 5712., 37123., 0., 25757.]
años = [2003, 1991, 1990, 2019, 2006]

In [44]:
datos = np.array([km, años])

In [45]:
datos

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [46]:
datos.shape

(2, 5)

![Numpy-img01.png](https://raw.githubusercontent.com/ElProfeAlejo/Bootcamp_Databases/main/imagenes/Numpy-img01.png)

In [47]:
datos[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [48]:
datos[1]

array([2003., 1991., 1990., 2019., 2006.])

In [49]:
km_media = datos[0] / (2024 - datos[1])
km_media

array([2114.76190476,  173.09090909, 1091.85294118,    0.        ,
       1430.94444444])

#**4. Selecciones con arrays Numpy**

![Numpy-img01.png](https://raw.githubusercontent.com/ElProfeAlejo/Bootcamp_Databases/main/imagenes/Numpy-img01.png)

In [50]:
datos

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

![1410-img02.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img02.png)

### Indexación

<font color=red>**Observación:**</font> La indexación tiene inicio en cero.

In [51]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
contador[0]

0

In [53]:
contador[9]

9

In [54]:
contador[-1]

9

In [55]:
datos[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [56]:
datos[1]

array([2003., 1991., 1990., 2019., 2006.])

### <font color=green>**Consejo:**</font>
### *ndarray[ linea ][ columna ]* o *ndarray[ linea, columna ]*

In [57]:
datos[1][2]

1990.0

In [58]:
datos[1,2]

1990.0

 ### Particiones

La sintaxis para realizar particiones en un array Numpy es $i : j : k$ donde $i$ es el índice inicial, $j$ es el índice final, y $k$ es el indicador de intervalo ($k\neq0$)

<font color=red>**Observación:**</font> En las particiones (*slices*) el objeto con índice i es **incluído** y el objeto con índice j **no es incluído** en el resultado.

![Numpy-img01.png](https://raw.githubusercontent.com/ElProfeAlejo/Bootcamp_Databases/main/imagenes/Numpy-img01.png)

In [60]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
contador[1:4:]

array([1, 2, 3])

In [62]:
contador[1:8:2]

array([1, 3, 5, 7])

In [63]:
contador[::2]

array([0, 2, 4, 6, 8])

In [64]:
contador[1::2]

array([1, 3, 5, 7, 9])

In [65]:
datos

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [66]:
datos[::,1:4:]

array([[ 5712., 37123.,     0.],
       [ 1991.,  1990.,  2019.]])

In [67]:
km_media = datos[::,1:4:][0] / (2024 - datos[::,1:4:][1])
km_media

array([ 173.09090909, 1091.85294118,    0.        ])

In [69]:
datos[0] / (2024 - datos[1])

array([2114.76190476,  173.09090909, 1091.85294118,    0.        ,
       1430.94444444])

### Indexación con array booleano

<font color=red>**Observación:**</font> Selecciona un grupo de líneas y columnas siguiendo las etiquetas o un array booleano.

In [70]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [72]:
contador[contador > 5]

array([6, 7, 8, 9])

In [73]:
datos

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [75]:
datos[1]>2000

array([ True, False, False,  True,  True])

In [76]:
datos[::,datos[1]>2000]

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])

#**5. Funciones Matemáticas de Numpy**

### Funciones Matemáticas:
- Numpy es una biblioteca especializada para operaciones matemáticas, y como tal, tenemos una variedad de funciones que nos ayudan a realizar estos cálculos:
https://numpy.org/doc/stable/reference/routines.math.html

### *power(array)*

Exponenciación de los elementos de un array.

In [88]:
m1 = np.array([3,2])
m1

array([3, 2])

In [90]:
np.power(m1,3)

array([27,  8])

### *array.max() y array.min()*

Elemento con valor máximo o mínimo en un array.

In [94]:
m1 = np.array([9,3,4,2,5,6,7])
m1

array([9, 3, 4, 2, 5, 6, 7])

In [95]:
m1.max()

9

In [96]:
m1.min()

2

### *add(array1, array2)*

Suma los elementos de 2 arrays.

In [97]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])

In [99]:
m1.shape

(2, 2)

$$
m_1 = \begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}
\quad
m_2 = \begin{pmatrix}
5 & 6 \\
7 & 8
\end{pmatrix}
$$


In [100]:
np.add(m1,m2)

array([[ 6,  8],
       [10, 12]])

### *subtract(array1, array2)*

Resta los elementos de 2 arrays.

In [101]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])

$$
m_1 = \begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}
\quad
m_2 = \begin{pmatrix}
5 & 6 \\
7 & 8
\end{pmatrix}
$$


In [102]:
np.subtract(m1,m2)

array([[-4, -4],
       [-4, -4]])

### *multiply(array1, array2)*

Multiplica los elementos de 2 arrays.

In [103]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])

$$
m_1 = \begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}
\quad
m_2 = \begin{pmatrix}
5 & 6 \\
7 & 8
\end{pmatrix}
$$


In [104]:
np.multiply(m1,m2)

array([[ 5, 12],
       [21, 32]])

### *divide(array1, array2)*

Divide los elementos de 2 arrays.

In [105]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])

$$
m_1 = \begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}
\quad
m_2 = \begin{pmatrix}
5 & 6 \\
7 & 8
\end{pmatrix}
$$


In [106]:
np.divide(m1,m2)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

#**6. Atributos y métodos de arrays Numpy**

## Atributos

In [108]:
datos

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

### *ndarray.shape*

Devuelve una tupla con las dimensiones del array.

In [109]:
datos.shape

(2, 5)

### *ndarray.ndim*

Devuelve el número de dimensiones del array.

In [110]:
datos.ndim

2

### *ndarray.size*

Devuelve el número de elementos del array.

In [111]:
datos.size

10

### *ndarray.dtype*

Devuelve el tipo de datos de los elementos del array.

In [112]:
datos.dtype

dtype('float64')

### *ndarray.T*

Devuelve el array transpuesto, es decir, convierte líneas en columnas y viceversa.

In [113]:
datos.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [114]:
datos.transpose()

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

## Métodos

### *ndarray.tolist()*

Devuelve el array como una lista Python.

In [115]:
datos.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

### *ndarray.reshape(shape[, order])*

Devuelve un array que contiene los mismos datos con una nueva forma.

In [122]:
contador=np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
contador.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [124]:
contador.reshape((5,2), order = 'C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [125]:
contador.reshape((5,2), order = 'F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [126]:
km = [44410, 5712, 37123, 0, 25757]
años = [2003, 1991, 1990, 2019, 2006]

In [127]:
info_motos = km + años
info_motos

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [130]:
np.array(info_motos).reshape((2,5))

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [132]:
np.array(info_motos).reshape((5,2), order = 'F')

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

### *ndarray.resize(new_shape[, refcheck])*

Cambia la forma y el tamaño del array.

In [134]:
datos_new = datos.copy()
datos_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [136]:
datos_new.resize((3,5), refcheck=False)

In [137]:
datos_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [138]:
datos_new[2] = datos_new[0] / (2024 - datos_new[1])

In [139]:
datos_new

array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2114.76190476,   173.09090909,  1091.85294118,     0.        ,
         1430.94444444]])

#**7. Estadísticas con arrays Numpy**

In [140]:
años = np.loadtxt(fname = "motos-fecha.txt", dtype = int)
km = np.loadtxt(fname = "motos-km.txt")
valor = np.loadtxt(fname = "motos-valor.txt")

In [143]:
valor.shape

(258,)

In [144]:
dataset = np.column_stack((años, km, valor))
dataset

array([[2.0070000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9950000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9940000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0240000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0100000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0160000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0240000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0130000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0140000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0150000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0060000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0110000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0050000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0240000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0130000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0200000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0160000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0240000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0200000e+03, 3.708

In [145]:
dataset.shape

(258, 3)

## *np.mean()*

Devuelve el promedio de los elementos del array a lo largo del eje especificado.

In [146]:
np.mean(dataset, axis = 0)

array([ 2012.46511628, 44499.41472868, 98960.51310078])

In [ ]:
np.mean(dataset, axis = 1)

In [148]:
np.mean(dataset[::, 1])

44499.41472868217

In [149]:
np.mean(dataset[::, 2])

98960.51310077519

## *np.std()*

Devuelve la desviación estándar de los elementos del array a lo largo del eje especificado.

In [150]:
np.std(dataset[::, 2])

29754.101150388564

## *ndarray.sum()*

Devuelve la suma de los elementos del array a lo largo del eje especificado.

In [151]:
dataset.sum(axis=0)

array([  519216.        , 11480849.        , 25531812.37999999])

In [152]:
dataset[::,1].sum()

11480849.0

## *np.sum()*

Devuelve la suma de los elementos del array a lo largo del eje especificado.

In [153]:
np.sum(dataset, axis = 0)

array([  519216.        , 11480849.        , 25531812.37999999])

In [154]:
np.sum(dataset[::, 1])

11480849.0

#**8. Algebra Lineal con Numpy**

### Algebra Lineal:
- NumPy ofrece funciones optimizadas para realizar cálculos de álgebra lineal de manera eficiente:
https://numpy.org/doc/stable/reference/routines.linalg.html

### *transpose(array)*

Devuelve la transpuesta de un array.

In [155]:
m1 = np.array([[1],[2],[3]])
m1

array([[1],
       [2],
       [3]])

In [156]:
m1.shape

(3, 1)

In [157]:
m1 = np.transpose(m1)
m1

array([[1, 2, 3]])

In [158]:
m1.shape

(1, 3)

### *reshape(array)*

Cambia la forma de un array.

In [159]:
m1 = np.array([[1],[2],[3]])
m1

array([[1],
       [2],
       [3]])

In [160]:
m1.shape

(3, 1)

In [161]:
m1 = m1.reshape(1,3)
m1

array([[1, 2, 3]])

In [162]:
m1.shape

(1, 3)

### *matmul(array1, array2)*

Útil para multiplicación de matrices.

In [163]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[1],[2],[3]])
print('M1:\n',m1)
print('-----')
print('M2:\n',m2)

M1:
 [[1 2 3]
 [4 5 6]]
-----
M2:
 [[1]
 [2]
 [3]]


La multiplicación de matrices se puede expresar como:

$$
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
\times
\begin{bmatrix}
1 \\
2 \\
3
\end{bmatrix}
=
\begin{bmatrix}
1 \cdot 1 + 2 \cdot 2 + 3 \cdot 3 \\
4 \cdot 1 + 5 \cdot 2 + 6 \cdot 3
\end{bmatrix}
=
\begin{bmatrix}
14 \\
32
\end{bmatrix}
$$

In [164]:
np.matmul(m1,m2)

array([[14],
       [32]])

### *dot(array1, array2)*

Más utilizado para multiplicación de matrices.

In [165]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])
print('M1:\n',m1)
print('-----')
print('M2:\n',m2)

M1:
 [[1 2]
 [3 4]]
-----
M2:
 [[5 6]
 [7 8]]


La multiplicación de matrices se puede expresar como:

$$
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
\times
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
=
\begin{bmatrix}
(1 \cdot 5 + 2 \cdot 7) & (1 \cdot 6 + 2 \cdot 8) \\
(3 \cdot 5 + 4 \cdot 7) & (3 \cdot 6 + 4 \cdot 8)
\end{bmatrix}
=
\begin{bmatrix}
19 & 22 \\
43 & 50
\end{bmatrix}
$$


In [166]:
np.dot(m1,m2)

array([[19, 22],
       [43, 50]])

### *linalg.solve(array1, array2)*

Facilita la resolución de ecuaciones de álgebra lineal.  
Se utiliza específicamente para resolver sistemas de ecuaciones lineales de la forma **Ax=B**, donde:

**A** es la matriz de coeficientes.  
**x** es el vector de variables desconocidas.  
**B** es el vector de resultados.  


####Ejercicio1

<h2>Resuelve la ecuación:</h2>

$$
Ax = B
$$

<h2>Donde:</h2>

$$
A = \begin{bmatrix}
2 & 1 & -2 \\
3 & 0 & 1 \\
1 & 1 & -1
\end{bmatrix}, \quad
B = \begin{bmatrix}
-3 \\
5 \\
-2
\end{bmatrix}
$$


In [167]:
A = np.array([[2,1,-2],[3,0,1],[1,1,-1]])
B = np.array([[-3],[5],[-2]])
print('A:\n',A)
print('-----')
print('B:\n',B)

A:
 [[ 2  1 -2]
 [ 3  0  1]
 [ 1  1 -1]]
-----
B:
 [[-3]
 [ 5]
 [-2]]


La ecuación se puede expresar como:

$$
\begin{bmatrix}
2 & 1 & -2 \\
3 & 0 & 1 \\
1 & 1 & -1
\end{bmatrix}
\begin{bmatrix}
x_0 \\
x_1 \\
x_2
\end{bmatrix}
=
\begin{bmatrix}
-3 \\
5 \\
-2
\end{bmatrix}
$$

In [168]:
x = np.linalg.solve(A, B)
x

array([[ 1.],
       [-1.],
       [ 2.]])

In [169]:
np.allclose(np.dot(A, x), B)

True

####Ejercicio2

<h2>Resuelve la ecuación:</h2>

$$
\begin{align*}
x_0 + 2x_1 & = 1 \\
3x_0 + 5x_1 & = 2
\end{align*}
$$

La multiplicación de matrices se puede expresar como:

$$
\begin{bmatrix}
x_0 + 2x_1 \\
3x_0 + 5x_1
\end{bmatrix}
=
\begin{bmatrix}
1 \\
2
\end{bmatrix}
$$

Esto se puede representar como:

$$
Ax = B
$$

$$
\begin{bmatrix}
1 & 2 \\
3 & 5
\end{bmatrix}
\begin{bmatrix}
x_0 \\
x_1
\end{bmatrix}
=
\begin{bmatrix}
1 \\
2
\end{bmatrix}
$$

Y al expandirlo, tenemos:

$$
\begin{bmatrix}
(1 \cdot x_0 + 2 \cdot x_1) \\
(3 \cdot x_0 + 5 \cdot x_1)
\end{bmatrix}
=
\begin{bmatrix}
1 \\
2
\end{bmatrix}
$$


In [170]:
A = np.array([[1, 2], [3, 5]])
B = np.array([1, 2])

In [171]:
x = np.linalg.solve(A, B)
x

array([-1.,  1.])

In [172]:
np.allclose(np.dot(A, x), B)

True

[<div align="left">
    <img src="https://raw.githubusercontent.com/ElProfeAlejo/Bootcamp_Databases/main/imagenes/email_abajo.png" alt="Texto alternativo" width="50%">](https://bootcampxperience.com/)